language: php

# Use container-based infrastructure
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source

script: vendor/bin/codecept run unit --coverage --report --coverage-xml

after_success:
 - mkdir build
 - mkdir build/logs
 - cp tests/_log/coverage.xml build/logs/clover.xml
 - php vendor/bin/coveralls -v
